http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        root /usr/share/nginx/html;
        #root ./shared_data/browser
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        # Enable directory listing (optional)
        autoindex on;
    }
}
